<a href="https://colab.research.google.com/github/Happday-bot/Happday-bot/blob/main/NumpyCheatSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: create a cheat sheet for numpy i, atleast 50 functions

import numpy as np

# Array Creation
np.array([1, 2, 3])  # Create an array from a list
np.zeros(5)  # Create an array of zeros
np.ones(3)  # Create an array of ones
np.arange(0, 10, 2)  # Create an array with a range of values
np.linspace(0, 1, 5) # Create an array with evenly spaced numbers
np.empty(4)  # Create an uninitialized array
np.full(3, 7) # Create an array filled with a specific value
np.eye(3)  # Create an identity matrix
np.random.rand(2, 3)  # Generate random numbers from a uniform distribution
np.random.randn(2, 3)  # Generate random numbers from a standard normal distribution
np.random.randint(0, 10, size=5) # Generate random integers within a range
np.random.choice([1,2,3], size=4) # Randomly sample from a given array
np.random.seed(42) # Set random seed for reproducibility


# Array Manipulation
np.reshape(np.array([1,2,3,4]), (2,2)) # Reshape an array
np.transpose(np.array([[1,2],[3,4]])) # Transpose an array
np.concatenate((np.array([1,2]), np.array([3,4]))) # Concatenate arrays
np.vstack((np.array([1,2]), np.array([3,4]))) # Vertical stack
np.hstack((np.array([1,2]), np.array([3,4]))) # Horizontal stack
np.split(np.array([1,2,3,4]), 2)  # Split an array into sub-arrays
np.delete(np.array([1,2,3]), 1) # Delete element at a specific index
np.insert(np.array([1,2,3]), 1, 4) # Insert element at a specific index
np.append(np.array([1,2,3]), 4) # Append element at the end


# Array Attributes
np.array([1, 2, 3]).ndim # Number of dimensions
np.array([1, 2, 3]).shape # Dimensions of the array
np.array([1, 2, 3]).size  # Total number of elements
np.array([1, 2, 3]).dtype  # Data type of elements


# Mathematical Operations
np.add(np.array([1,2]), np.array([3,4])) # Element-wise addition
np.subtract(np.array([1,2]), np.array([3,4])) # Element-wise subtraction
np.multiply(np.array([1,2]), np.array([3,4])) # Element-wise multiplication
np.divide(np.array([1,2]), np.array([3,4])) # Element-wise division
np.dot(np.array([1,2]), np.array([3,4])) # Dot product
np.sum(np.array([1,2,3])) # Sum of elements
np.mean(np.array([1,2,3])) # Mean of elements
np.std(np.array([1,2,3])) # Standard deviation of elements
np.min(np.array([1,2,3])) # Minimum element
np.max(np.array([1,2,3])) # Maximum element
np.argmin(np.array([1,2,3])) # Index of minimum element
np.argmax(np.array([1,2,3])) # Index of maximum element

# Linear Algebra
np.linalg.inv(np.array([[1,2],[3,4]])) # Inverse of a matrix
np.linalg.det(np.array([[1,2],[3,4]]))  # Determinant of a matrix
np.linalg.eig(np.array([[1,2],[3,4]]))  # Eigenvalues and eigenvectors


#Other Useful Functions
np.unique(np.array([1,1,2,2,3])) # Find unique elements
np.where(np.array([1,2,3]) > 1) # Find indices where condition is true
np.sort(np.array([3,1,2])) # Sort the array
np.argsort(np.array([3,1,2])) # Indices that would sort the array
np.any(np.array([1,0,0]) > 0) # Checks if any element satisfies condition
np.all(np.array([1,2,3]) > 0) # Checks if all element satisfies condition

In [ ]:
# prompt: generate another 50 functions as cheat sheet

import numpy as np

# Array Filtering and Selection
np.where(np.array([1, 2, 3]) > 1)  # Indices where condition is true
np.extract(np.array([1, 2, 3]) > 1, np.array([1, 2, 3])) # Elements where condition is true

# Array Statistics
np.median(np.array([1, 2, 3])) # Median of elements
np.percentile(np.array([1, 2, 3]), 50)  # Percentile of elements

# Mathematical Functions
np.abs(np.array([-1, 2]))  # Absolute values
np.sqrt(np.array([4,9])) # Square root of elements
np.square(np.array([2,3])) # Square of elements
np.power(np.array([2,3]), 2)  # Raise elements to a power
np.exp(np.array([1,2])) # Exponential of elements
np.log(np.array([np.e, np.e**2]))  # Natural logarithm of elements
np.log10(np.array([10, 100])) # Base-10 logarithm of elements

# Trigonometric Functions
np.sin(np.array([0, np.pi/2])) # Sine of elements
np.cos(np.array([0, np.pi/2])) # Cosine of elements
np.tan(np.array([0, np.pi/4])) # Tangent of elements
np.arcsin(np.array([0, 1])) # Inverse sine
np.arccos(np.array([1, 0])) # Inverse cosine
np.arctan(np.array([0, 1])) # Inverse tangent

# Rounding Functions
np.round(np.array([1.2, 1.7])) # Round to nearest integer
np.floor(np.array([1.2, 1.7])) # Round down
np.ceil(np.array([1.2, 1.7])) # Round up
np.trunc(np.array([1.2, 1.7])) # Truncate towards zero

# Comparison Functions
np.greater(np.array([1,2]), np.array([2,1])) # Element-wise greater than
np.less(np.array([1,2]), np.array([2,1]))  # Element-wise less than
np.equal(np.array([1,2]), np.array([1,2]))  # Element-wise equality

# Logical Operations
np.logical_and(np.array([True, False]), np.array([True, True])) # Element-wise logical AND
np.logical_or(np.array([True, False]), np.array([True, True])) # Element-wise logical OR
np.logical_not(np.array([True, False])) # Element-wise logical NOT

# Other useful functions
np.clip(np.array([-1, 0, 1]), -0.5, 0.5) # Clip values within a range
np.ptp(np.array([1,2,3,4,5])) # Peak-to-peak (range) value


# Advanced Array Manipulation
np.roll(np.array([1,2,3]), 1) # Roll elements
np.rot90(np.array([[1,2],[3,4]])) # Rotate array 90 degrees
np.flip(np.array([1,2,3]))  # Reverse elements
np.fliplr(np.array([[1,2],[3,4]])) # Flip array left to right
np.flipud(np.array([[1,2],[3,4]])) # Flip array up to down


# Saving and Loading
# np.save('my_array.npy', np.array([1, 2, 3]))  # Save array to a file
# np.load('my_array.npy')  # Load array from a file

In [ ]:
# prompt: save all above functions as a google doc file

from google.colab import files

# Create a string containing the code to be saved
code_content = """import numpy as np


# Array Creation
np.array([1, 2, 3])  # Create an array from a list
np.zeros(5)  # Create an array of zeros
np.ones(3)  # Create an array of ones
np.arange(0, 10, 2)  # Create an array with a range of values
np.linspace(0, 1, 5) # Create an array with evenly spaced numbers
np.empty(4)  # Create an uninitialized array
np.full(3, 7) # Create an array filled with a specific value
np.eye(3)  # Create an identity matrix
np.random.rand(2, 3)  # Generate random numbers from a uniform distribution
np.random.randn(2, 3)  # Generate random numbers from a standard normal distribution
np.random.randint(0, 10, size=5) # Generate random integers within a range
np.random.choice([1,2,3], size=4) # Randomly sample from a given array
np.random.seed(42) # Set random seed for reproducibility


# Array Manipulation
np.reshape(np.array([1,2,3,4]), (2,2)) # Reshape an array
np.transpose(np.array([[1,2],[3,4]])) # Transpose an array
np.concatenate((np.array([1,2]), np.array([3,4]))) # Concatenate arrays
np.vstack((np.array([1,2]), np.array([3,4]))) # Vertical stack
np.hstack((np.array([1,2]), np.array([3,4]))) # Horizontal stack
np.split(np.array([1,2,3,4]), 2)  # Split an array into sub-arrays
np.delete(np.array([1,2,3]), 1) # Delete element at a specific index
np.insert(np.array([1,2,3]), 1, 4) # Insert element at a specific index
np.append(np.array([1,2,3]), 4) # Append element at the end


# Array Attributes
np.array([1, 2, 3]).ndim # Number of dimensions
np.array([1, 2, 3]).shape # Dimensions of the array
np.array([1, 2, 3]).size  # Total number of elements
np.array([1, 2, 3]).dtype  # Data type of elements


# Mathematical Operations
np.add(np.array([1,2]), np.array([3,4])) # Element-wise addition
np.subtract(np.array([1,2]), np.array([3,4])) # Element-wise subtraction
np.multiply(np.array([1,2]), np.array([3,4])) # Element-wise multiplication
np.divide(np.array([1,2]), np.array([3,4])) # Element-wise division
np.dot(np.array([1,2]), np.array([3,4])) # Dot product
np.sum(np.array([1,2,3])) # Sum of elements
np.mean(np.array([1,2,3])) # Mean of elements
np.std(np.array([1,2,3])) # Standard deviation of elements
np.min(np.array([1,2,3])) # Minimum element
np.max(np.array([1,2,3])) # Maximum element
np.argmin(np.array([1,2,3])) # Index of minimum element
np.argmax(np.array([1,2,3])) # Index of maximum element

# Linear Algebra
np.linalg.inv(np.array([[1,2],[3,4]])) # Inverse of a matrix
np.linalg.det(np.array([[1,2],[3,4]]))  # Determinant of a matrix
np.linalg.eig(np.array([[1,2],[3,4]]))  # Eigenvalues and eigenvectors


#Other Useful Functions
np.unique(np.array([1,1,2,2,3])) # Find unique elements
np.where(np.array([1,2,3]) > 1) # Find indices where condition is true
np.sort(np.array([3,1,2])) # Sort the array
np.argsort(np.array([3,1,2])) # Indices that would sort the array
np.any(np.array([1,0,0]) > 0) # Checks if any element satisfies condition
np.all(np.array([1,2,3]) > 0) # Checks if all element satisfies condition


# Array Filtering and Selection
np.where(np.array([1, 2, 3]) > 1)  # Indices where condition is true
np.extract(np.array([1, 2, 3]) > 1, np.array([1, 2, 3])) # Elements where condition is true

# Array Statistics
np.median(np.array([1, 2, 3])) # Median of elements
np.percentile(np.array([1, 2, 3]), 50)  # Percentile of elements

# Mathematical Functions
np.abs(np.array([-1, 2]))  # Absolute values
np.sqrt(np.array([4,9])) # Square root of elements
np.square(np.array([2,3])) # Square of elements
np.power(np.array([2,3]), 2)  # Raise elements to a power
np.exp(np.array([1,2])) # Exponential of elements
np.log(np.array([np.e, np.e**2]))  # Natural logarithm of elements
np.log10(np.array([10, 100])) # Base-10 logarithm of elements

# Trigonometric Functions
np.sin(np.array([0, np.pi/2])) # Sine of elements
np.cos(np.array([0, np.pi/2])) # Cosine of elements
np.tan(np.array([0, np.pi/4])) # Tangent of elements
np.arcsin(np.array([0, 1])) # Inverse sine
np.arccos(np.array([1, 0])) # Inverse cosine
np.arctan(np.array([0, 1])) # Inverse tangent

# Rounding Functions
np.round(np.array([1.2, 1.7])) # Round to nearest integer
np.floor(np.array([1.2, 1.7])) # Round down
np.ceil(np.array([1.2, 1.7])) # Round up
np.trunc(np.array([1.2, 1.7])) # Truncate towards zero

# Comparison Functions
np.greater(np.array([1,2]), np.array([2,1])) # Element-wise greater than
np.less(np.array([1,2]), np.array([2,1]))  # Element-wise less than
np.equal(np.array([1,2]), np.array([1,2]))  # Element-wise equality

# Logical Operations
np.logical_and(np.array([True, False]), np.array([True, True])) # Element-wise logical AND
np.logical_or(np.array([True, False]), np.array([True, True])) # Element-wise logical OR
np.logical_not(np.array([True, False])) # Element-wise logical NOT

# Other useful functions
np.clip(np.array([-1, 0, 1]), -0.5, 0.5) # Clip values within a range
np.ptp(np.array([1,2,3,4,5])) # Peak-to-peak (range) value


# Advanced Array Manipulation
np.roll(np.array([1,2,3]), 1) # Roll elements
np.rot90(np.array([[1,2],[3,4]])) # Rotate array 90 degrees
np.flip(np.array([1,2,3]))  # Reverse elements
np.fliplr(np.array([[1,2],[3,4]])) # Flip array left to right
np.flipud(np.array([[1,2],[3,4]])) # Flip array up to down


# Saving and Loading
# np.save('my_array.npy', np.array([1, 2, 3]))  # Save array to a file
# np.load('my_array.npy')  # Load array from a file"""

with open('numpy_functions.txt', 'w') as f:
  f.write(code_content)

files.download('numpy_functions.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:

import numpy as np

# Array Creation
print(np.array([1, 2, 3]))  # Create an array from a list
print(np.zeros(5))  # Create an array of zeros
print(np.ones(3))  # Create an array of ones
print(np.arange(0, 10, 2))  # Create an array with a range of values
print(np.linspace(0, 1, 5)) # Create an array with evenly spaced numbers
print(np.empty(4))  # Create an uninitialized array
print(np.full(3, 7)) # Create an array filled with a specific value
print(np.eye(3))  # Create an identity matrix
print(np.random.rand(2, 3))  # Generate random numbers from a uniform distribution
print(np.random.randn(2, 3))  # Generate random numbers from a standard normal distribution
print(np.random.randint(0, 10, size=5)) # Generate random integers within a range
print(np.random.normal(loc=0, scale=1, size=10)) #generates random numbers from a normal (Gaussian) distribution with specified mean and standard deviation
print(np.random.choice([1,2,3], size=4)) # Randomly sample from a given array
np.random.seed(42) # Set random seed for reproducibility


# Array Manipulation
print(np.reshape(np.array([1,2,3,4]), (2,2))) # Reshape an array
print(np.transpose(np.array([[1,2],[3,4]]))) # Transpose an array
print(np.concatenate((np.array([1,2]), np.array([3,4])))) # Concatenate arrays
print(np.vstack((np.array([1,2]), np.array([3,4])))) # Vertical stack
print(np.hstack((np.array([1,2]), np.array([3,4])))) # Horizontal stack
print(np.split(np.array([1,2,3,4]), 2))  # Split an array into sub-arrays
print(np.delete(np.array([1,2,3]), 1)) # Delete element at a specific index
print(np.insert(np.array([1,2,3]), 1, 4)) # Insert element at a specific index
print(np.append(np.array([1,2,3]), 4)) # Append element at the end


# Array Attributes
print(np.array([1, 2, 3]).ndim) # Number of dimensions
print(np.array([1, 2, 3]).shape) # Dimensions of the array
print(np.array([1, 2, 3]).size)  # Total number of elements
print(np.array([1, 2, 3]).dtype)  # Data type of elements


# Mathematical Operations
print(np.add(np.array([1,2]), np.array([3,4]))) # Element-wise addition
print(np.subtract(np.array([1,2]), np.array([3,4]))) # Element-wise subtraction
print(np.multiply(np.array([1,2]), np.array([3,4]))) # Element-wise multiplication
print(np.divide(np.array([1,2]), np.array([3,4]))) # Element-wise division
print(np.dot(np.array([1,2]), np.array([3,4]))) # Dot product
print(np.sum(np.array([1,2,3]))) # Sum of elements
print(np.mean(np.array([1,2,3]))) # Mean of elements
print(np.std(np.array([1,2,3]))) # Standard deviation of elements
print(np.min(np.array([1,2,3]))) # Minimum element
print(np.max(np.array([1,2,3]))) # Maximum element
print(np.argmin(np.array([1,2,3]))) # Index of minimum element
print(np.argmax(np.array([1,2,3]))) # Index of maximum element

# Linear Algebra
print(np.linalg.inv(np.array([[1,2],[3,4]]))) # Inverse of a matrix
print(np.linalg.det(np.array([[1,2],[3,4]])))  # Determinant of a matrix
print(np.linalg.eig(np.array([[1,2],[3,4]])))  # Eigenvalues and eigenvectors


#Other Useful Functions
print(np.unique(np.array([1,1,2,2,3]))) # Find unique elements
print(np.where(np.array([1,2,3]) > 1)) # Find indices where condition is true
print(np.sort(np.array([3,1,2]))) # Sort the array
print(np.argsort(np.array([3,1,2]))) # Indices that would sort the array
print(np.any(np.array([1,0,0]) > 0)) # Checks if any element satisfies condition
print(np.all(np.array([1,2,3]) > 0)) # Checks if all element satisfies condition


# Array Filtering and Selection
print(np.where(np.array([1, 2, 3]) > 1))  # Indices where condition is true
print(np.extract(np.array([1, 2, 3]) > 1, np.array([1, 2, 3]))) # Elements where condition is true

# Array Statistics
print(np.median(np.array([1, 2, 3]))) # Median of elements
print(np.percentile(np.array([1, 2, 3]), 50))  # Percentile of elements

# Mathematical Functions
print(np.abs(np.array([-1, 2])))  # Absolute values
print(np.sqrt(np.array([4,9]))) # Square root of elements
print(np.square(np.array([2,3]))) # Square of elements
print(np.power(np.array([2,3]), 2))  # Raise elements to a power
print(np.exp(np.array([1,2]))) # Exponential of elements
print(np.log(np.array([np.e, np.e**2])))  # Natural logarithm of elements
print(np.log10(np.array([10, 100]))) # Base-10 logarithm of elements

# Trigonometric Functions
print(np.sin(np.array([0, np.pi/2]))) # Sine of elements
print(np.cos(np.array([0, np.pi/2]))) # Cosine of elements
print(np.tan(np.array([0, np.pi/4]))) # Tangent of elements
print(np.arcsin(np.array([0, 1]))) # Inverse sine
print(np.arccos(np.array([1, 0]))) # Inverse cosine
print(np.arctan(np.array([0, 1]))) # Inverse tangent

# Rounding Functions
print(np.round(np.array([1.2, 1.7]))) # Round to nearest integer
print(np.floor(np.array([1.2, 1.7]))) # Round down
print(np.ceil(np.array([1.2, 1.7]))) # Round up
print(np.trunc(np.array([1.2, 1.7]))) # Truncate towards zero

# Comparison Functions
print(np.greater(np.array([1,2]), np.array([2,1]))) # Element-wise greater than
print(np.less(np.array([1,2]), np.array([2,1])))  # Element-wise less than
print(np.equal(np.array([1,2]), np.array([1,2])))  # Element-wise equality

# Logical Operations
print(np.logical_and(np.array([True, False]), np.array([True, True]))) # Element-wise logical AND
print(np.logical_or(np.array([True, False]), np.array([True, True]))) # Element-wise logical OR
print(np.logical_not(np.array([True, False]))) # Element-wise logical NOT

# Other useful functions
print(np.clip(np.array([-1, 0, 1]), -0.5, 0.5)) # Clip values within a range
print(np.ptp(np.array([1,2,3,4,5]))) # Peak-to-peak (range) value


# Advanced Array Manipulation
print(np.roll(np.array([1,2,3]), 1)) # Roll elements
print(np.rot90(np.array([[1,2],[3,4]]))) # Rotate array 90 degrees
print(np.flip(np.array([1,2,3])))  # Reverse elements
print(np.fliplr(np.array([[1,2],[3,4]]))) # Flip array left to right
print(np.flipud(np.array([[1,2],[3,4]]))) # Flip array up to down


#Outlier detection
print(np.percentile([2,3,4,6,8,9,10,45], 25))
print(np.percentile([2,3,4,6,8,9,10,45], 75))

[1 2 3]
[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.25 0.5  0.75 1.  ]
[7 7 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
[9 5 8 0 9]
[-0.25104397 -0.16386712 -1.47632969  1.48698096 -0.02445518  0.35555132
  0.41701111  0.83246186 -0.29339915 -0.02983857]
[1 2 2 2]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4])]
[1 3]
[1 4 2 3]
[1 2 3 4]
1
(3,)
3
int64
[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]
11
6
2.0
0.816496580927726
1
3
0
2
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[1 2 3]
(array([1, 2]),)
[1 2 3]
[1 2 0]
True
True
(array([1, 2]),)
[2 3]
2.0
2.0
[1 2]
[2. 3.]
[4 9]
[4 9]
[2.71828183 7.3890561 ]
[1. 2.]
[1. 2.]
[0. 1.]


In [ ]:
# prompt: give more functions of nummpy for data preprocessing

import numpy as np

# ... (Your existing code)

# Outlier detection using IQR
data = np.array([2, 3, 4, 6, 8, 9, 10, 45])
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data < lower_bound) | (data > upper_bound)]
print("Outliers using IQR:", outliers)


#Normalization (Min-Max scaling)
data = np.array([1, 5, 10, 15, 20])
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized data:", normalized_data)


#Standardization (Z-score normalization)
data = np.array([1, 5, 10, 15, 20])
standardized_data = (data - np.mean(data)) / np.std(data)
print("Standardized data:", standardized_data)


#Binarization
data = np.array([1, 5, 10, 15, 20])
threshold = 10
binarized_data = np.where(data > threshold, 1, 0)
print("Binarized data:", binarized_data)


#Imputation (using mean)
data = np.array([1, 5, np.nan, 15, 20])
mean_value = np.nanmean(data)
imputed_data = np.nan_to_num(data, nan=mean_value)
print("Imputed data:", imputed_data)

# One-hot encoding (example for a single feature)
labels = np.array(['red', 'green', 'blue', 'red'])
unique_labels = np.unique(labels)
one_hot_encoded = np.zeros((len(labels), len(unique_labels)))
for i, label in enumerate(labels):
  one_hot_encoded[i, np.where(unique_labels == label)] = 1
print("One-hot encoded labels:\n",one_hot_encoded)

In [ ]:
# prompt: add more functions like mean, median mode and assigning nan

import numpy as np
from scipy import stats

# ... (Your existing code)

# Calculate mean, median, and mode
data = np.array([1, 2, 3, 4, 5, 5, 6])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Mode:", stats.mode(data)[0][0])  # Use scipy.stats.mode for mode

# Assign NaN values
data_with_nan = np.array([1, 2, np.nan, 4, 5])
print("Data with NaN:", data_with_nan)